// Core Emotle Game Data and Constants
const EPOCH_START_DATE = new Date('2024-01-01T00:00:00Z');
const MS_PER_DAY = 1000 * 60 * 60 * 24;

const emojiPhrases = [
    // Animals (30)
    { emoji: "🐶", answer: "DOG" },
    { emoji: "🐱", answer: "CAT" },
    { emoji: "🐻", answer: "BEAR" },
    { emoji: "🦊", answer: "FOX" },
    { emoji: "🐷", answer: "PIG" },
    { emoji: "🐠", answer: "FISH" },
    { emoji: "🦋", answer: "BUTTERFLY" },
    { emoji: "🐝", answer: "BEE" },
    { emoji: "🦉", answer: "OWL" },
    { emoji: "🐎", answer: "HORSE" },
    { emoji: "🐘", answer: "ELEPHANT" },
    { emoji: "🦒", answer: "GIRAFFE" },
    { emoji: "🐒", answer: "MONKEY" },
    { emoji: "🐧", answer: "PENGUIN" },
    { emoji: "🐢", answer: "TURTLE" },
    { emoji: "🐍", answer: "SNAKE" },
    { emoji: "🐅", answer: "TIGER" },
    { emoji: "🦓", answer: "ZEBRA" },
    { emoji: "🐳", answer: "WHALE" },
    { emoji: "🐬", answer: "DOLPHIN" },
    { emoji: "🐦", answer: "BIRD" },
    { emoji: "🦆", answer: "DUCK" },
    { emoji: "🐓", answer: "ROOSTER" },
    { emoji: "🐇", answer: "RABBIT" },
    { emoji: "🐿️", answer: "SQUIRREL" },
    { emoji: "🐾", answer: "PAWS" },
    { emoji: "🐜", answer: "ANT" },
    { emoji: "🕷️", "answer": "SPIDER" },
    { emoji: "🦂", answer: "SCORPION" },
    { emoji: "🦀", answer: "CRAB" },

    // Food/Drink (40)
    { emoji: "🍕", answer: "PIZZA" },
    { emoji: "🍔", answer: "BURGER" },
    { emoji: "🍟", answer: "FRIES" },
    { emoji: "🍩", answer: "DONUT" },
    { emoji: "🍦", answer: "ICECREAM" },
    { emoji: "☕", answer: "COFFEE" },
    { emoji: "🥤", answer: "SODA" },
    { emoji: "🍎", answer: "APPLE" },
    { emoji: "🍌", answer: "BANANA" },
    { emoji: "🥕", answer: "CARROT" },
    { emoji: "🥦", answer: "BROCCOLI" },
    { emoji: "🍞", answer: "BREAD" },
    { emoji: "🧀", answer: "CHEESE" },
    { emoji: "🍳", answer: "EGG" },
    { emoji: "🍬", answer: "CANDY" },
    { emoji: "🍫", answer: "CHOCOLATE" },
    { emoji: "🍓", answer: "STRAWBERRY" },
    { emoji: "🌽", answer: "CORN" },
    { emoji: "🍚", answer: "RICE" },
    { emoji: "🍜", answer: "NOODLES" },
    { emoji: "🍇", answer: "GRAPES" },
    { emoji: "🍉", answer: "WATERMELON" },
    { emoji: "🍋", answer: "LEMON" },
    { emoji: "🍑", answer: "PEACH" },
    { emoji: "🍒", answer: "CHERRY" },
    { emoji: "🍍", answer: "PINEAPPLE" },
    { emoji: "🥑", answer: "AVOCADO" },
    { emoji: "🌶️", answer: "CHILI" },
    { emoji: "🧅", answer: "ONION" },
    { emoji: "🥔", answer: "POTATO" },
    { emoji: "🍄", answer: "MUSHROOM" },
    { emoji: "🥒", answer: "CUCUMBER" },
    { emoji: "🥜", answer: "PEANUTS" },
    { emoji: "🍯", answer: "HONEY" },
    { emoji: "🧂", answer: "SALT" },
    { emoji: "🍪", answer: "COOKIE" },
    { emoji: "🎂", answer: "CAKE" },
    { emoji: "🧁", answer: "CUPCAKE" },
    { emoji: "🍩🍩", answer: "DOUGHNUT" },
    { emoji: "☕🍵", answer: "TEA" },

    // Nature/Weather (25)
    { emoji: "☀️", answer: "SUN" },
    { emoji: "🌙", answer: "MOON" },
    { emoji: "🌟", answer: "STAR" },
    { emoji: "🌧️", answer: "RAIN" },
    { emoji: "🌳", answer: "TREE" },
    { emoji: "🌸", answer: "FLOWER" },
    { emoji: "🌊", answer: "WAVE" },
    { emoji: "🔥", answer: "FIRE" },
    { emoji: "⛰️", answer: "MOUNTAIN" },
    { emoji: "❄️", answer: "SNOW" },
    { emoji: "🌎", answer: "EARTH" },
    { emoji: "🌈", answer: "RAINBOW" },
    { emoji: "💧", answer: "WATER" },
    { emoji: "🌪️", answer: "TORNADO" },
    { emoji: "🌬️", answer: "WIND" },
    { emoji: "☁️", answer: "CLOUD" },
    { emoji: "⚡", answer: "LIGHTNING" },
    { emoji: "☔", answer: "UMBRELLA" },
    { emoji: "🌱", answer: "PLANT" },
    { emoji: "🍂", answer: "AUTUMN" },
    { emoji: "☀️⛱️", answer: "BEACH" },
    { emoji: "🌋", answer: "VOLCANO" },
    { emoji: "🧊", answer: "ICE" },
    { emoji: "🏜️", answer: "DESERT" },
    { emoji: "🌌", answer: "GALAXY" },

    // Objects/Tech/Home (60)
    { emoji: "💡", answer: "LIGHT" },
    { emoji: "⏰", answer: "CLOCK" },
    { emoji: "📚", answer: "BOOK" },
    { emoji: "🎮", answer: "GAME" },
    { emoji: "🚗", answer: "CAR" },
    { emoji: "✈️", answer: "PLANE" },
    { emoji: "🚀", answer: "ROCKET" },
    { emoji: "🚢", answer: "SHIP" },
    { emoji: "🏠", answer: "HOUSE" },
    { emoji: "🏫", answer: "SCHOOL" },
    { emoji: "🏥", answer: "HOSPITAL" },
    { emoji: "🏢", answer: "BUILDING" },
    { emoji: "📱", answer: "PHONE" },
    { emoji: "💻", answer: "COMPUTER" },
    { emoji: "📺", answer: "TELEVISION" },
    { emoji: "📸", answer: "CAMERA" },
    { emoji: "🎤", answer: "MICROPHONE" },
    { emoji: "🎸", answer: "GUITAR" },
    { emoji: "🥁", answer: "DRUMS" },
    { emoji: "⚽", answer: "SOCCER" },
    { emoji: "🏀", answer: "BASKETBALL" },
    { emoji: "🏈", answer: "FOOTBALL" },
    { emoji: "⚾", answer: "BASEBALL" },
    { emoji: "🎾", answer: "TENNIS" },
    { emoji: "🚲", answer: "BICYCLE" },
    { emoji: "🔑", answer: "KEY" },
    { emoji: "🎁", answer: "GIFT" },
    { emoji: "✉️", answer: "LETTER" },
    { emoji: "📍", answer: "LOCATION" },
    { emoji: "💰", answer: "MONEY" },
    { emoji: "💎", answer: "DIAMOND" },
    { emoji: "🛡️", answer: "SHIELD" },
    { emoji: "⚙️", answer: "GEAR" },
    { emoji: "🧪", answer: "FLASK" },
    { emoji: "🔬", answer: "MICROSCOPE" },
    { emoji: "🔭", answer: "TELESCOPE" },
    { emoji: "🗺️", answer: "MAP" },
    { emoji: "📝", answer: "PAD" },
    { emoji: "✂️", answer: "SCISSORS" },
    { emoji: "🪚", answer: "SAW" },
    { emoji: "🔨", answer: "HAMMER" },
    { emoji: "🔧", answer: "WRENCH" },
    { emoji: "📏", answer: "RULER" },
    { emoji: "🗓️", answer: "CALENDAR" },
    { emoji: "🗑️", answer: "TRASH" },
    { emoji: "🔓", answer: "UNLOCK" },
    { emoji: "🔒", answer: "LOCK" },
    { emoji: "🧳", answer: "LUGGAGE" },
    { emoji: "🎒", answer: "BACKPACK" },
    { emoji: "💼", answer: "BRIEFCASE" },
    { emoji: "📦", answer: "BOX" },
    { emoji: "🛒", answer: "CART" },
    { emoji: "🛎️", answer: "BELL" },
    { emoji: "🪞", answer: "MIRROR" },
    { emoji: "🛋️", answer: "SOFA" },
    { emoji: "🪑", answer: "CHAIR" },
    { emoji: "🛏️", answer: "BED" },
    { emoji: "🚽", answer: "TOILET" },
    { emoji: "🚿", answer: "SHOWER" },
    { emoji: "🛁", answer: "BATHTUB" },

    // Professions/People (20)
    { emoji: "👨‍🍳", answer: "CHEF" },
    { emoji: "👩‍⚕️", answer: "DOCTOR" },
    { emoji: "👨‍💻", answer: "PROGRAMMER" },
    { emoji: "👩‍🏫", answer: "TEACHER" },
    { emoji: "👮‍♂️", answer: "POLICE" },
    { emoji: "👨‍🚀", answer: "ASTRONAUT" },
    { emoji: "👨‍👩‍👧‍👦", answer: "FAMILY" },
    { emoji: "🧑‍🤝‍🧑", answer: "FRIENDS" },
    { emoji: "🧑‍🎓", answer: "STUDENT" },
    { emoji: "🧑‍🎤", answer: "SINGER" },
    { emoji: "🧑‍🎨", answer: "ARTIST" },
    { emoji: "🧑‍✈️", answer: "PILOT" },
    { emoji: "🧑‍🚒", answer: "FIREFIGHT" },
    { emoji: "🧑‍🏭", answer: "WORKER" },
    { emoji: "🧑‍🌾", answer: "FARMER" },
    { emoji: "🧑‍🔧", answer: "MECHANIC" },
    { emoji: "🧑‍🔬", answer: "SCIENTIST" },
    { emoji: "🧑‍⚖️", answer: "JUDGE" },
    { emoji: "🧑‍💼", answer: "OFFICER" },
    { emoji: "👶", answer: "BABY" },

    // Emotions/Actions (20)
    { emoji: "❤️", answer: "LOVE" },
    { emoji: "😄", answer: "HAPPY" },
    { emoji: "😭", answer: "CRYING" },
    { emoji: "🏃‍♀️", answer: "RUNNING" },
    { emoji: "🛌", answer: "SLEEPING" },
    { emoji: "🚶‍♂️", answer: "WALKING" },
    { emoji: "💃", answer: "DANCING" },
    { emoji: "🕺", answer: "DANCING" },
    { emoji: "🗣️", answer: "SPEAKING" },
    { emoji: "👍", answer: "APPROVE" },
    { emoji: "👎", answer: "DISAPPROVE" },
    { emoji: "💯", answer: "PERFECT" },
    { emoji: "🥳", answer: "CELEBRATE" },
    { emoji: "🤔", answer: "THINKING" },
    { emoji: "😡", answer: "ANGRY" },
    { emoji: "😅", answer: "SWEATING" },
    { emoji: "🤩", answer: "AMAZING" },
    { emoji: "😴", answer: "SLEEPY" },
    { emoji: "🤯", answer: "SHOCKED" },
    { emoji: "😩", answer: "TIRED" },

    // Pop Culture/Themes (25)
    { emoji: "👑🎤", answer: "QUEEN" },
    { emoji: "🎸⚡", answer: "ROCK" },
    { emoji: "⭐️", answer: "FAME" },
    { emoji: "🕷️🕸️", answer: "SPIDEY" },
    { emoji: "🚀🌌", answer: "SPACE" },
    { emoji: "🦸‍♂️🏙️", answer: "BATMAN" },
    { emoji: "🏎️🏁", answer: "RACING" },
    { emoji: "🦖🦕", answer: "DINOS" },
    { emoji: "🤖👽", answer: "SCI-FI" },
    { emoji: "🧚‍♀️✨", answer: "FAIRY" },
    { emoji: "👻🎃", answer: "HALLOWEEN" },
    { emoji: "🎅🎁", answer: "SANTA" },
    { emoji: "🎄🌟", answer: "CHRISTMAS" },
    { emoji: "🐣🥚", answer: "EASTER" },
    { emoji: "🏈🏆", answer: "TOUCHDOWN" },
    { emoji: "🏀 hoops", answer: "HOOPS" },
    { emoji: "⚾🏟️", answer: "STADIUM" },
    { emoji: "🎾 court", answer: "COURT" },
    { emoji: "🌊 surf", answer: "SURFING" },
    { emoji: "🏂❄️", answer: "SNOWBOARD" },
    { emoji: "🎿⛷️", answer: "SKIING" },
    { emoji: "🧘‍♀️☮️", answer: "YOGA" },
    { emoji: "🎨🖌️", answer: "ART" },
    { emoji: "📷🎞️", answer: "PHOTO" },
    { emoji: "🎬🍿", answer: "MOVIE" },

    // More Objects/General (35) - To reach 200 total
    { emoji: "🏠🌳", answer: "GARDEN" },
    { emoji: "🚪", answer: "DOOR" },
    { emoji: "🪟", answer: "WINDOW" },
    { emoji: "💡💡💡", answer: "BRIGHT" },
    { emoji: "🔑🚪", answer: "LOCK" },
    { emoji: "✉️📬", answer: "MAIL" },
    { emoji: "📦📦", answer: "PACKAGE" },
    { emoji: "🧮", answer: "ABACUS" },
    { emoji: "📐", answer: "ANGLE" },
    { emoji: "📍📍", answer: "PINS" },
    { emoji: "🗺️🌐", answer: "WORLD" },
    { emoji: "🌍", answer: "PLANET" },
    { emoji: "🧭", answer: "COMPASS" },
    { emoji: "🔭🪐", answer: "ORBIT" },
    { emoji: "🧪🔬", answer: "SCIENCE" },
    { emoji: "💉", answer: "NEEDLE" },
    { emoji: "💊", answer: "PILL" },
    { emoji: "🩻", answer: "XRAY" },
    { emoji: "🩹", answer: "BANDAGE" },
    { emoji: "🩸", answer: "BLOOD" },
    { emoji: "📊", answer: "GRAPH" },
    { emoji: "📉", answer: "DECREASE" },
    { emoji: "📈", answer: "INCREASE" },
    { emoji: "🔔", answer: "BELL" },
    { emoji: "🎶", answer: "MUSIC" },
    { emoji: "🎧", answer: "EARBUDS" },
    { emoji: "🗣️💬", answer: "CHAT" },
    { emoji: "✍️", answer: "WRITE" },
    { emoji: "📅", answer: "DATE" },
    { emoji: "📝", answer: "NOTE" },
    { emoji: "🧽", answer: "SPONGE" },
    { emoji: "🪣", answer: "BUCKET" },
    { emoji: "🧹", answer: "BROOM" },
    { emoji: "🧻", answer: "TISSUE" },
    { emoji: "✂️🧵", answer: "SEWING" },
    // Additional entries to reach 200
    { emoji: "🗺️🧭", answer: "JOURNEY" },
    { emoji: "🗣️📢", answer: "SPEECH" },
    { emoji: "👓", answer: "GLASSES" },
    { emoji: "🕶️", answer: "SUNGLASS" },
    { emoji: "👕", answer: "SHIRT" },
    { emoji: "👖", answer: "PANTS" },
    { emoji: "👗", answer: "DRESS" },
    { emoji: "🧥", answer: "COAT" },
    { emoji: "👟", answer: "SNEAKERS" },
    { emoji: "👠", answer: "HEELS" },
    { emoji: "👢", answer: "BOOTS" },
    { emoji: "🎩", answer: "HAT" },
    { emoji: "🧣", answer: "SCARF" },
    { emoji: "🧤", answer: "GLOVES" },
    { emoji: "💍", answer: "RING" },
    { emoji: " necklace", answer: "NECKLACE" },
    { emoji: "💎✨", answer: "JEWELS" },
    { emoji: "🕰️", answer: "GRANDFATH" }, // Grandfather Clock (9 chars)
    { emoji: "🎈", answer: "BALLOON" },
    { emoji: "🎉", answer: "PARTY" },
    { emoji: "🎊", answer: "CELEBRATE" },
    { emoji: "🎁🎀", answer: "PRESENT" },
    { emoji: "🎂🕯️", answer: "BIRTHDAY" },
    { emoji: "🥳🎶", answer: "FESTIVAL" },
    { emoji: "🎭", answer: "ACTING" },
    { emoji: "🎻", answer: "VIOLIN" },
    { emoji: "🎺", answer: "TRUMPET" },
    { emoji: "🎷", answer: "SAXOPHONE" },
    { emoji: "🥁🥁", answer: "DRUMMING" },
    { emoji: "🎹", answer: "PIANO" },
    { emoji: "🎼", answer: "MELODY" },
    { emoji: "🎙️", answer: "VOCALS" },
    { emoji: "🖼️", answer: "PAINTING" },
    { emoji: "🗿", answer: "STATUE" },
    { emoji: "🏺", answer: "VASE" },
    { emoji: "🏹", answer: "ARCHERY" },
    { emoji: "Fishing", answer: "FISHING" },
    { emoji: "🧗‍♀️", answer: "CLIMBING" },
    { emoji: "🚴‍♂️", answer: "CYCLING" },
    { emoji: "🚣‍♀️", answer: "ROWING" },
    { emoji: "🏊‍♀️", answer: "SWIMMING" },
    { emoji: "Surfing", answer: "SURFING" },
    { emoji: "🤽‍♂️", answer: "WATERPOLO" }, // 9 chars
    { emoji: "🤸‍♂️", answer: "GYMNAST" },
    { emoji: "🤺", answer: "FENCING" },
    { emoji: "🥋", answer: "KARATE" },
    { emoji: "🥊", answer: "BOXING" },
    { emoji: "🤼‍♂️", answer: "WRESTLING" },
    { emoji: "🥅", answer: "GOAL" },
    { emoji: "🏒", answer: "HOCKEY" },
    { emoji: " skating", answer: "SKATING" },
    { emoji: "🛷", answer: "SLEDDING" },
    { emoji: "🎯🏹", answer: "ARCHER" },
    { emoji: "Bowling", answer: "BOWLING" },
    { emoji: "🎲", answer: "DICE" },
    { emoji: "🧩", answer: "PUZZLE" },
    { emoji: "🧸", answer: "TEDDY" },
    { emoji: "🪀", answer: "YOYO" },
    { emoji: " Kite", answer: "KITE" },
    { emoji: "🚂💨", answer: "TRAIN" },
    { emoji: "🚒", answer: "FIRETRUCK" }, // 9 chars
    { emoji: "🚔", answer: "POLICECAR" }, // 9 chars
    { emoji: "🚕", answer: "TAXI" },
    { emoji: "🚌", answer: "BUS" },
    { emoji: "Train", answer: "SUBWAY" },
    { emoji: "Ferry", answer: "FERRY" },
    { emoji: "🚁", answer: "HELICOPTER" }, // 10 chars
    { emoji: "🛰️", answer: "SATELLITE" }, // 9 chars
    { emoji: "🛎️🛎️", answer: "SERVICE" },
    { emoji: "🛎️🚪", answer: "DOORBELL" }
];
